"""#764: artifact publication is generated by the UoW, not the legacy writer."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

LIB = Path(__file__).resolve().parents[1] / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))


def _state_module():
    path = Path(__file__).resolve().parents[1] / "bin" / "mission-state.py"
    spec = importlib.util.spec_from_file_location("issue764_state", path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize(
    "sid",
    ("", "plain", ".hidden", ". foo", " leading", "a/b", r"a\\b", "ends "),
)
def test_artifact_rule_accepts_every_sanitized_session_segment(sid):
    from mission_kernel.projection_path import (
        ProjectionRejection,
        resolve_internal_artifact_path,
    )

    segment = _state_module()._sanitize_sid(sid)
    resolved = resolve_internal_artifact_path(
        Path(f".mission-state/artifacts/{segment}/mission-artifact.md"),
        root_name=".mission-state",
    )
    assert not isinstance(resolved, ProjectionRejection)


@pytest.mark.parametrize(
    "path",
    (
        ".mission-state/artifacts//mission-artifact.md",
        ".mission-state/artifacts/.hidden/mission-artifact.md",
        ".mission-state/artifacts/x/other.md",
        ".mission-state/archive/iter-1-abcdef01-progress.md",
    ),
)
def test_artifact_rule_refuses_any_other_internal_shape(path):
    from mission_kernel.projection_path import (
        ProjectionRejection,
        resolve_internal_artifact_path,
    )

    assert isinstance(
        resolve_internal_artifact_path(Path(path), root_name=".mission-state"),
        ProjectionRejection,
    )


def test_artifact_rule_refuses_a_path_deeper_than_its_four_parts():
    from mission_kernel.projection_path import (
        ProjectionRejection,
        resolve_internal_artifact_path,
    )

    resolved = resolve_internal_artifact_path(
        Path(".mission-state/artifacts/test/mission-artifact.md/extra"),
        root_name=".mission-state",
    )
    assert isinstance(resolved, ProjectionRejection)


@pytest.mark.parametrize("segment", ("foo ", "foo\t"))
def test_artifact_rule_refuses_trailing_whitespace_in_a_segment(segment):
    from mission_kernel.projection_path import (
        ProjectionRejection,
        resolve_internal_artifact_path,
    )

    resolved = resolve_internal_artifact_path(
        Path(f".mission-state/artifacts/{segment}/mission-artifact.md"),
        root_name=".mission-state",
    )
    assert isinstance(resolved, ProjectionRejection)


def test_artifact_rule_allows_a_leading_space_from_sanitized_session_id():
    from mission_kernel.projection_path import (
        ProjectionRejection,
        resolve_internal_artifact_path,
    )

    segment = _state_module()._sanitize_sid(". foo")
    resolved = resolve_internal_artifact_path(
        Path(f".mission-state/artifacts/{segment}/mission-artifact.md"),
        root_name=".mission-state",
    )
    assert segment == " foo"
    assert not isinstance(resolved, ProjectionRejection)

def test_authorisation_is_bound_to_command_and_effect_field():
    from mission_application.evidence_publication import (
        EvidencePublicationError,
        authorize_generated_destinations,
    )

    artifact = ".mission-state/artifacts/test/mission-artifact.md"
    for command in (
        "initialize-artifact",
        "render-artifact",
        "record-artifact-publication",
    ):
        authorize_generated_destinations(
            (artifact,), command_type=command, field="effect"
        )
    authorize_generated_destinations(
        (artifact,), command_type="export-artifact", field="artifact_effect"
    )
    for command, field in (("export-artifact", "export_effect"), ("update-progress", "effect")):
        with pytest.raises(EvidencePublicationError) as caught:
            authorize_generated_destinations(
                (artifact,), command_type=command, field=field
            )
        assert caught.value.code == "publication-destination-unauthorized"


def test_artifact_markdown_does_not_include_updated_at():
    rendered = _state_module()._render_artifact_markdown(
        {"session_id": "test", "updated_at": "2030-01-01T00:00:01Z"},
        {"updated_at": "2030-01-01T00:00:02Z"},
    )
    assert "updated_at" not in rendered


def test_every_effect_command_has_a_publication_path_field():
    from mission_application.evidence_publication import (
        EFFECT_FIELDS_BY_COMMAND_TYPE,
        PUBLICATION_PATH_FIELD_BY_COMMAND_TYPE,
    )

    assert set(EFFECT_FIELDS_BY_COMMAND_TYPE) <= set(PUBLICATION_PATH_FIELD_BY_COMMAND_TYPE)


def _generated_blob(path, *, digest="sha256:" + "0" * 64, size=0):
    from mission_application.evidence_publication import derive_blob_id
    from mission_persistence.evidence_order import published_binding_type
    from mission_persistence.local_uow import VerifiedBlob

    binding = published_binding_type()(
        blob_id=derive_blob_id(path), kind="artifact", relative_path=path,
        digest=digest, size=size, origin="generated", target=path,
    )
    return VerifiedBlob(binding, b"")


def _blob_set(*blobs):
    from mission_persistence.local_uow import VerifiedBlobSet

    return VerifiedBlobSet(blobs)


def _entry_refuses(command_type, *blobs):
    from mission_persistence.fenced_commit import (
        FencedCommitError,
        refuse_unauthorized_generated_blobs,
    )

    with pytest.raises(FencedCommitError) as caught:
        refuse_unauthorized_generated_blobs(command_type, _blob_set(*blobs))
    assert caught.value.code == "request-invalid"


def test_entry_allows_zero_or_projection_blobs_but_rejects_wrong_internal_rule():
    from mission_persistence.fenced_commit import refuse_unauthorized_generated_blobs

    projection = _generated_blob("docs/a.md")
    refuse_unauthorized_generated_blobs("update-progress", _blob_set())
    refuse_unauthorized_generated_blobs("update-progress", _blob_set(projection))
    _entry_refuses(
        "initialize-artifact",
        _generated_blob(".mission-state/archive/iter-1-abcdef01-progress.md"),
    )


def test_entry_export_requires_two_equal_generated_blobs_when_nonempty():
    from mission_persistence.fenced_commit import refuse_unauthorized_generated_blobs

    artifact = _generated_blob(".mission-state/artifacts/test/mission-artifact.md")
    projection = _generated_blob("docs/a.md")
    _entry_refuses("export-artifact", artifact)
    refuse_unauthorized_generated_blobs("export-artifact", _blob_set(
        artifact, _generated_blob("docs/a.md")
    ))
    _entry_refuses(
        "export-artifact", artifact,
        _generated_blob("docs/a.md", digest="sha256:" + "1" * 64),
    )


def test_entry_derives_internal_permissions_from_the_field_rule_table(monkeypatch):
    from mission_application import evidence_publication
    from mission_persistence.fenced_commit import refuse_unauthorized_generated_blobs

    artifact = _generated_blob(".mission-state/artifacts/test/mission-artifact.md")
    refuse_unauthorized_generated_blobs("render-artifact", _blob_set(artifact))
    monkeypatch.delitem(
        evidence_publication.INTERNAL_DESTINATION_RULE_BY_COMMAND_FIELD,
        ("render-artifact", "effect"),
    )
    _entry_refuses("render-artifact", artifact)


@pytest.mark.parametrize(
    ("command_type", "first", "second"),
    (
        (
            "render-artifact",
            ".mission-state/artifacts/one/mission-artifact.md",
            ".mission-state/artifacts/two/mission-artifact.md",
        ),
        (
            "update-progress",
            ".mission-state/archive/iter-1-abcdef01-progress.md",
            ".mission-state/archive/iter-2-abcdef01-progress.md",
        ),
    ),
)
def test_entry_refuses_two_internal_blobs_even_when_each_rule_is_permitted(
    command_type, first, second
):
    _entry_refuses(command_type, _generated_blob(first), _generated_blob(second))


def test_entry_refuses_a_render_binding_redirected_to_a_projection():
    _entry_refuses("render-artifact", _generated_blob("docs/redirected.md"))


@pytest.mark.parametrize("command_type", ("update-progress", "unknown-command"))
def test_entry_does_not_let_captured_blobs_bypass_internal_destination_rules(command_type):
    blob = _generated_blob(".mission-state/artifacts/victim/mission-artifact.md")
    blob = blob.__class__(
        blob.binding.__class__(**{**blob.binding.__dict__, "origin": "captured"}),
        blob.content,
    )
    _entry_refuses(command_type, blob)


@pytest.mark.parametrize("directory", ("sessions", "commits"))
def test_artifact_rule_refuses_other_repository_directories(directory):
    from mission_kernel.projection_path import ProjectionRejection, resolve_internal_artifact_path

    assert isinstance(resolve_internal_artifact_path(
        Path(f".mission-state/{directory}/x/mission-artifact.md"), root_name=".mission-state"
    ), ProjectionRejection)


def test_entry_refuses_export_with_both_blobs_inside_the_repository():
    """The count alone does not carry this: two in-root blobs are two blobs.

    Checker of #764: the in-root upper bound had no test that reached it,
    because the only two-in-root case used a command whose blob count is one,
    where the count refused it first.
    """
    # Both are the artifact rule, which this command is allowed, so only the
    # upper bound can refuse them.  Mixing in a progress path would be
    # refused for the rule instead and leave the bound untested.
    _entry_refuses("export-artifact", *(
        _generated_blob(path) for path in (
            ".mission-state/artifacts/test/mission-artifact.md",
            ".mission-state/artifacts/other/mission-artifact.md",
        )
    ))


def test_entry_refuses_export_with_three_equal_blobs():
    _entry_refuses("export-artifact", *(
        _generated_blob(path) for path in (
            ".mission-state/artifacts/test/mission-artifact.md", "docs/a.md", "docs/b.md"
        )
    ))


def test_entry_refuses_progress_target_redirected_to_projection():
    blob = _generated_blob("docs/victim-progress.md")
    blob = blob.__class__(blob.binding.__class__(**{
        **blob.binding.__dict__,
        "target": ".mission-state/archive/iter-1-abcdef01-progress.md",
    }), blob.content)
    _entry_refuses("update-progress", blob)


def test_entry_refuses_export_projection_target_redirected_to_another_path():
    artifact = _generated_blob(".mission-state/artifacts/test/mission-artifact.md")
    projection = _generated_blob("docs/victim-export.md")
    projection = projection.__class__(projection.binding.__class__(**{
        **projection.binding.__dict__, "target": "docs/intended.md",
    }), projection.content)
    _entry_refuses("export-artifact", artifact, projection)


def test_entry_refuses_captured_progress_target_redirected_to_projection():
    blob = _generated_blob("docs/victim-progress.md")
    blob = blob.__class__(blob.binding.__class__(**{
        **blob.binding.__dict__, "origin": "captured",
        "target": ".mission-state/archive/iter-1-abcdef01-progress.md",
    }), blob.content)
    _entry_refuses("update-progress", blob)


def test_entry_refuses_captured_export_target_redirected_to_projection():
    artifact = _generated_blob(".mission-state/artifacts/test/mission-artifact.md")
    projection = _generated_blob("docs/victim-export.md")
    projection = projection.__class__(projection.binding.__class__(**{
        **projection.binding.__dict__, "origin": "captured", "target": "docs/intended.md",
    }), projection.content)
    _entry_refuses("export-artifact", artifact, projection)


def test_entry_allows_render_when_target_matches_its_canonical_path():
    from mission_persistence.fenced_commit import refuse_unauthorized_published_blobs
    path = ".mission-state/artifacts/test/mission-artifact.md"
    blob = _generated_blob(path)
    blob = blob.__class__(blob.binding.__class__(**{**blob.binding.__dict__, "target": path}), blob.content)
    refuse_unauthorized_published_blobs("render-artifact", _blob_set(blob))


def test_export_to_state_root_is_refused_before_any_write(state_dir, run_cli, read_state):
    root = state_dir.parent
    assert run_cli("artifact", "init", "--json", cwd=root).returncode == 0
    state_path = state_dir / "sessions" / "test.json"
    before = state_path.read_bytes()

    result = run_cli(
        "artifact", "export", "--to", ".mission-state/export.md",
        "--redaction-status", "reviewed", "--json", cwd=root,
    )

    assert result.returncode == 2
    assert "publication-path-invalid" in result.stderr
    assert state_path.read_bytes() == before
    assert not (root / ".mission-state" / "export.md").exists()
    assert read_state(state_dir) == __import__("json").loads(before)


def test_v4_export_to_state_root_is_refused_before_any_write(legacy_run_cli, tmp_path):
    assert legacy_run_cli("init", "artifact v4", cwd=tmp_path).returncode == 0
    assert legacy_run_cli("artifact", "init", cwd=tmp_path).returncode == 0
    state_path = tmp_path / ".mission-state" / "sessions" / "test.json"
    before = state_path.read_bytes()
    result = legacy_run_cli(
        "artifact", "export", "--to", ".mission-state/export.md",
        "--redaction-status", "reviewed", cwd=tmp_path,
    )
    assert result.returncode == 2
    assert "publication-path-invalid" in result.stderr
    assert state_path.read_bytes() == before


def _case_insensitive(root) -> bool:
    """Say whether this filesystem opens one directory under two spellings."""
    probe = root / ".mission-state"
    try:
        return (root / ".MISSION-STATE").stat().st_ino == probe.stat().st_ino
    except OSError:
        return False


def test_v4_export_through_a_symlink_to_the_state_root_is_refused(legacy_run_cli, tmp_path):
    """A name is not the directory it opens.

    The v4 route has no filesystem-identity layer of its own, so this entry is
    the only place that stops the write.  A symlink reaches the repository
    under a name the string comparison accepts.
    """
    assert legacy_run_cli("init", "artifact v4", cwd=tmp_path).returncode == 0
    assert legacy_run_cli("artifact", "init", cwd=tmp_path).returncode == 0
    (tmp_path / "alias").symlink_to(tmp_path / ".mission-state", target_is_directory=True)
    state_path = tmp_path / ".mission-state" / "sessions" / "test.json"
    before = state_path.read_bytes()

    result = legacy_run_cli(
        "artifact", "export", "--to", "alias/export.md",
        "--redaction-status", "reviewed", cwd=tmp_path,
    )

    assert result.returncode == 2
    assert "publication-path-invalid" in result.stderr
    assert state_path.read_bytes() == before
    assert not (tmp_path / ".mission-state" / "export.md").exists()


def test_v4_export_under_another_spelling_of_the_state_root_is_refused(legacy_run_cli, tmp_path):
    """On a filesystem that ignores case, ``.MISSION-STATE`` is the repository."""
    assert legacy_run_cli("init", "artifact v4", cwd=tmp_path).returncode == 0
    assert legacy_run_cli("artifact", "init", cwd=tmp_path).returncode == 0
    if not _case_insensitive(tmp_path):
        pytest.skip("this filesystem distinguishes the two spellings")
    state_path = tmp_path / ".mission-state" / "sessions" / "test.json"
    before = state_path.read_bytes()

    result = legacy_run_cli(
        "artifact", "export", "--to", ".MISSION-STATE/export.md",
        "--redaction-status", "reviewed", cwd=tmp_path,
    )

    assert result.returncode == 2
    assert "publication-path-invalid" in result.stderr
    assert state_path.read_bytes() == before
    assert not (tmp_path / ".mission-state" / "export.md").exists()


def test_an_export_beside_the_repository_still_passes(legacy_run_cli, tmp_path):
    """The rule refuses the repository, not every directory near it."""
    assert legacy_run_cli("init", "artifact v4", cwd=tmp_path).returncode == 0
    assert legacy_run_cli("artifact", "init", cwd=tmp_path).returncode == 0
    (tmp_path / "docs").mkdir()

    result = legacy_run_cli(
        "artifact", "export", "--to", "docs/export.md",
        "--redaction-status", "reviewed", cwd=tmp_path,
    )

    assert result.returncode == 0, result.stderr
    assert (tmp_path / "docs" / "export.md").exists()


def test_artifact_rendered_bytes_are_time_independent_but_input_sensitive():
    from mission_application.artifact import prepare_artifact_init

    render = _state_module()._render_artifact_markdown
    state = {"session_id": "test", "mission": "one"}
    def prepared(now, title="title"):
        return prepare_artifact_init(
            state, now=now,
            artifact_path=".mission-state/artifacts/test/mission-artifact.md",
            format="markdown", title=title, redaction_status="unchecked",
            required_for_pass=False,
            render=lambda document, artifact: render(document, artifact).encode(),
        ).effects[0].content
    assert prepared("2026-01-01T00:00:00Z") == prepared("2031-06-30T23:59:59Z")
    assert prepared("2026-01-01T00:00:00Z", "other") != prepared("2026-01-01T00:00:00Z")
